@echo off
echo Starting HazID Generator...
echo.
echo Step 1: Starting Vite dev server...
start "Vite Dev Server" cmd /k "npm run dev"
echo.
echo Step 2: Waiting 5 seconds for server to start...
timeout /t 5 /nobreak >nul
echo.
echo Step 3: Starting Electron app...
npm run electron-dev-simple
pause 