/**
 * Electron Main Process
 * 
 * This file handles the main Electron process including:
 * - Window management and application lifecycle
 * - File system operations (Excel reading, draft saving/loading)
 * - IPC communication with renderer process
 * - Application menu setup
 * - Security configuration
 */

const { app, BrowserWindow, ipcMain, dialog, shell, Menu } = require('electron');
const path = require('path');
const fs = require('fs');
const XLSX = require('xlsx');

let mainWindow;

/**
 * Create the application menu bar
 * 
 * Sets up the menu structure with File, Edit, and Help menus.
 * Includes keyboard shortcuts for common operations like save, load, and export.
 */
function createApplicationMenu() {
  const template = [
    {
      label: 'File',
      submenu: [
        {
          label: 'New Document',
          accelerator: 'CmdOrCtrl+N',
          click: () => {
            // Reload the app to start fresh
            mainWindow.reload();
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Save Draft',
          accelerator: 'CmdOrCtrl+S',
          click: async () => {
            mainWindow.webContents.send('menu-save-draft');
          }
        },
        {
          label: 'Load Draft',
          accelerator: 'CmdOrCtrl+O',
          click: async () => {
            mainWindow.webContents.send('menu-load-draft');
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Export Document',
          accelerator: 'CmdOrCtrl+E',
          click: () => {
            mainWindow.webContents.send('menu-export-document');
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Open Uploads Folder',
          click: async () => {
            try {
              const result = await getUploadsDirectory();
              if (result.success) {
                // Create uploads folder if it doesn't exist
                if (!fs.existsSync(result.path)) {
                  fs.mkdirSync(result.path, { recursive: true });
                  
                  // Create a README file to explain the purpose
                  const readmeContent = `# Uploads Folder

This folder is used for:
- Storing uploaded documents and attachments
- Temporary files during document generation
- Draft files and backup data

You can safely delete files in this folder if needed.

Generated by HazID Generator - CERN CMS Safety Team
`;
                  fs.writeFileSync(path.join(result.path, 'README.txt'), readmeContent);
                }
                
                shell.showItemInFolder(result.path);
              } else {
                await dialog.showMessageBox(mainWindow, {
                  type: 'error',
                  title: 'Cannot Open Uploads Folder',
                  message: `Error accessing uploads folder:\n\n${result.error}`
                });
              }
            } catch (error) {
              console.error('Error opening uploads folder:', error);
              await dialog.showMessageBox(mainWindow, {
                type: 'error',
                title: 'Cannot Open Uploads Folder',
                message: `Error opening uploads folder:\n\n${error.message}`
              });
            }
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Exit',
          accelerator: process.platform === 'darwin' ? 'Cmd+Q' : 'Ctrl+Q',
          click: () => {
            app.quit();
          }
        }
      ]
    },
    {
      label: 'Edit',
      submenu: [
        {
          label: 'Undo',
          accelerator: 'CmdOrCtrl+Z',
          role: 'undo'
        },
        {
          label: 'Redo',
          accelerator: 'Shift+CmdOrCtrl+Z',
          role: 'redo'
        },
        {
          type: 'separator'
        },
        {
          label: 'Cut',
          accelerator: 'CmdOrCtrl+X',
          role: 'cut'
        },
        {
          label: 'Copy',
          accelerator: 'CmdOrCtrl+C',
          role: 'copy'
        },
        {
          label: 'Paste',
          accelerator: 'CmdOrCtrl+V',
          role: 'paste'
        },
        {
          type: 'separator'
        },
        {
          label: 'Select All',
          accelerator: 'CmdOrCtrl+A',
          role: 'selectall'
        }
      ]
    },
    {
      label: 'View',
      submenu: [
        {
          label: 'Reload',
          accelerator: 'CmdOrCtrl+R',
          click: () => {
            mainWindow.reload();
          }
        },
        {
          label: 'Force Reload',
          accelerator: 'CmdOrCtrl+Shift+R',
          click: () => {
            mainWindow.webContents.reloadIgnoringCache();
          }
        },
        {
          label: 'Toggle Developer Tools',
          accelerator: process.platform === 'darwin' ? 'Alt+Cmd+I' : 'Ctrl+Shift+I',
          click: () => {
            mainWindow.webContents.toggleDevTools();
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Actual Size',
          accelerator: 'CmdOrCtrl+0',
          click: () => {
            mainWindow.webContents.setZoomLevel(0);
          }
        },
        {
          label: 'Zoom In',
          accelerator: 'CmdOrCtrl+Plus',
          click: () => {
            const currentZoom = mainWindow.webContents.getZoomLevel();
            mainWindow.webContents.setZoomLevel(currentZoom + 1);
          }
        },
        {
          label: 'Zoom Out',
          accelerator: 'CmdOrCtrl+-',
          click: () => {
            const currentZoom = mainWindow.webContents.getZoomLevel();
            mainWindow.webContents.setZoomLevel(currentZoom - 1);
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Toggle Fullscreen',
          accelerator: process.platform === 'darwin' ? 'Ctrl+Cmd+F' : 'F11',
          click: () => {
            mainWindow.setFullScreen(!mainWindow.isFullScreen());
          }
        }
      ]
    },
    {
      label: 'Tools',
      submenu: [
        {
          label: 'Check Excel Data',
          click: async () => {
            try {
              const excelPath = path.join(process.cwd(), 'data', 'excel', 'CMS_Safety-List_Preventive_Protective_Measures.xlsx');
              
              if (!fs.existsSync(excelPath)) {
                await dialog.showMessageBox(mainWindow, {
                  type: 'warning',
                  title: 'Excel File Not Found',
                  message: `Excel file not found at:\n${excelPath}\n\nPlease ensure the Excel file exists in the data/excel/ folder.`
                });
                return;
              }
              
              const workbook = XLSX.readFile(excelPath);
              const sheetNames = workbook.SheetNames;
              const hseSheet = workbook.Sheets['HSE Sheet'];
              
              if (!hseSheet) {
                await dialog.showMessageBox(mainWindow, {
                  type: 'warning',
                  title: 'HSE Sheet Not Found',
                  message: `HSE Sheet not found in Excel file.\n\nAvailable sheets: ${sheetNames.join(', ')}`
                });
                return;
              }
              
              const hseData = XLSX.utils.sheet_to_json(hseSheet);
              
              await dialog.showMessageBox(mainWindow, {
                type: 'info',
                title: 'Excel Data Check - Success',
                message: `Excel file loaded successfully!\n\nFile: ${path.basename(excelPath)}\nSheets found: ${sheetNames.length}\nHSE Sheet entries: ${hseData.length}\n\nHazard categories available:\n${hseData.map(item => `• ${item['Hazard Category'] || 'Unknown'}`).join('\n')}`
              });
            } catch (error) {
              await dialog.showMessageBox(mainWindow, {
                type: 'error',
                title: 'Excel Data Check Failed',
                message: `Error checking Excel data:\n\n${error.message}`
              });
            }
          }
        },
        {
          label: 'Validate Form Data',
          click: async () => {
            await dialog.showMessageBox(mainWindow, {
              type: 'info',
              title: 'Validate Form Data',
              message: 'To validate your form data:\n\n1. Complete all required fields\n2. Select at least one hazard category\n3. The Export button will be enabled when validation passes\n\nUse the progress indicator at the bottom to see completion status.'
            });
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Create/Open External Data Folder',
          click: async () => {
            try {
              let dataDir, excelDir;
              if (app.isPackaged) {
                dataDir = path.join(process.resourcesPath, '..', 'data');
                excelDir = path.join(dataDir, 'excel');
              } else {
                dataDir = path.join(process.cwd(), 'data');
                excelDir = path.join(dataDir, 'excel');
              }

              // Create directories if they don't exist
              if (!fs.existsSync(dataDir)) {
                fs.mkdirSync(dataDir, { recursive: true });
              }
              if (!fs.existsSync(excelDir)) {
                fs.mkdirSync(excelDir, { recursive: true });
              }

              // Copy Excel files if they don't exist externally
              const sourceDir = app.isPackaged 
                ? path.join(process.resourcesPath, 'app', 'data', 'excel')
                : path.join(process.cwd(), 'data', 'excel');

              const filesToCopy = [
                'CMS_Safety-List_Preventive_Protective_Measures.xlsx',
                'CMS_Safety-Location_TSO_Links_Reference.xlsx'
              ];

              let copiedFiles = 0;
              for (const fileName of filesToCopy) {
                const sourcePath = path.join(sourceDir, fileName);
                const targetPath = path.join(excelDir, fileName);
                
                if (fs.existsSync(sourcePath) && !fs.existsSync(targetPath)) {
                  fs.copyFileSync(sourcePath, targetPath);
                  copiedFiles++;
                }
              }

              // Show success message
              const message = copiedFiles > 0 
                ? `External data folder created successfully!\n\n${copiedFiles} Excel file(s) copied.\n\nYou can now modify these files and changes will be reflected in the application.`
                : 'External data folder already exists.\n\nYou can modify the Excel files and changes will be reflected in the application.';

              await dialog.showMessageBox(mainWindow, {
                type: 'info',
                title: 'External Data Folder',
                message: message,
                detail: `Location: ${excelDir}`,
                buttons: ['Open Folder', 'OK']
              }).then((result) => {
                if (result.response === 0) {
                  shell.showItemInFolder(excelDir);
                }
              });

            } catch (error) {
              console.error('Error creating external data folder:', error);
              dialog.showMessageBox(mainWindow, {
                type: 'error',
                title: 'Error',
                message: 'Failed to create external data folder',
                detail: error.message,
                buttons: ['OK']
              });
            }
          }
        }
      ]
    },
    {
      label: 'Help',
      submenu: [
        {
          label: 'About CERN CMS Safety',
          click: () => {
            dialog.showMessageBox(mainWindow, {
              type: 'info',
              title: 'About CERN CMS Safety',
              message: 'CERN CMS Safety - Hazard Identification Generator',
              detail: 'Version 1.0.0\n\nThis application helps generate hazard identification documents for CERN CMS Safety activities.\n\nDeveloped for CERN CMS Safety Team',
              buttons: ['OK']
            });
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'CERN HSE Website',
          click: () => {
            shell.openExternal('https://hse.cern/');
          }
        },
        {
          label: 'CMS Safety Website',
          click: () => {
            shell.openExternal('https://cmssafety.web.cern.ch/');
          }
        },
        {
          type: 'separator'
        },
        {
          label: 'Keyboard Shortcuts',
          click: () => {
            dialog.showMessageBox(mainWindow, {
              type: 'info',
              title: 'Keyboard Shortcuts',
              message: 'Keyboard Shortcuts',
              detail: 'File Operations:\n' +
                     'Ctrl+N - New Document\n' +
                     'Ctrl+S - Save Draft\n' +
                     'Ctrl+O - Load Draft\n' +
                     'Ctrl+E - Export Document\n\n' +
                     'Edit Operations:\n' +
                     'Ctrl+Z - Undo\n' +
                     'Ctrl+Y - Redo\n' +
                     'Ctrl+C - Copy\n' +
                     'Ctrl+V - Paste\n\n' +
                     'View Operations:\n' +
                     'Ctrl+R - Reload\n' +
                     'F11 - Toggle Fullscreen\n' +
                     'Ctrl+0 - Reset Zoom\n' +
                     'Ctrl++ - Zoom In\n' +
                     'Ctrl+- - Zoom Out',
              buttons: ['OK']
            });
          }
        }
      ]
    }
  ];

  // macOS specific menu adjustments
  if (process.platform === 'darwin') {
    template.unshift({
      label: app.getName(),
      submenu: [
        {
          label: 'About ' + app.getName(),
          role: 'about'
        },
        {
          type: 'separator'
        },
        {
          label: 'Services',
          role: 'services',
          submenu: []
        },
        {
          type: 'separator'
        },
        {
          label: 'Hide ' + app.getName(),
          accelerator: 'Command+H',
          role: 'hide'
        },
        {
          label: 'Hide Others',
          accelerator: 'Command+Shift+H',
          role: 'hideothers'
        },
        {
          label: 'Show All',
          role: 'unhide'
        },
        {
          type: 'separator'
        },
        {
          label: 'Quit',
          accelerator: 'Command+Q',
          click: () => {
            app.quit();
          }
        }
      ]
    });
  }

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
}

// Helper function for uploads directory
async function getUploadsDirectory() {
  try {
    let uploadsDir;
    if (app.isPackaged) {
      uploadsDir = path.join(process.resourcesPath, '..', 'uploads');
    } else {
      uploadsDir = path.join(process.cwd(), 'uploads');
    }
    return { success: true, path: uploadsDir };
  } catch (error) {
    console.error('Error getting uploads directory:', error);
    return { success: false, error: error.message };
  }
}

/**
 * Create the main application window
 * 
 * Initializes the BrowserWindow with security settings, loads the appropriate
 * content (dev server or built files), and sets up window event handlers.
 */
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 1000,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js')
    },
    icon: path.join(__dirname, './src/assets/Logo CMS Safety.png')
  });

  const isDev = !app.isPackaged;
  
  if (isDev) {
    // Development mode - load from Vite dev server
    // Try to load from dev server first, fall back to built files
    mainWindow.loadURL('http://localhost:5173').catch(() => {
      // Development server not available - fallback to built files
      mainWindow.loadFile(path.join(__dirname, '../dist/index.html'));
    });
    mainWindow.webContents.openDevTools();
  } else {
    // Production mode - load from built files
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  // Handle window closed
  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

app.whenReady().then(() => {
  createApplicationMenu();
  createWindow();
  
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// IPC Handlers);


ipcMain.handle('read-excel-file', async (event, filePath, sheetName, headerRow = 0) => {
  try {
    let fullPath = filePath;
    
    // Handle relative paths - try external data folder first, then embedded files
    if (!path.isAbsolute(filePath)) {
      if (app.isPackaged) {
        // First try external data folder (next to the executable)
        const externalDataPath = path.join(process.resourcesPath, '..', filePath);
        if (fs.existsSync(externalDataPath)) {
          fullPath = externalDataPath;
          console.log('Using external data file:', fullPath);
        } else {
          // Fall back to embedded files
          const appPath = path.join(process.resourcesPath, 'app');
          fullPath = path.join(appPath, filePath);
          console.log('Using embedded data file:', fullPath);
        }
      } else {
        // In development, use project files
        fullPath = path.join(process.cwd(), filePath);
      }
    }
    
    // Attempt to read Excel file from resolved path
    if (!fs.existsSync(fullPath)) {
      throw new Error(`File not found: ${fullPath}`);
    }
    
    const workbook = XLSX.readFile(fullPath);
    const worksheet = workbook.Sheets[sheetName];
    
    if (!worksheet) {
      throw new Error(`Sheet '${sheetName}' not found in workbook`);
    }
    
    const data = XLSX.utils.sheet_to_json(worksheet, {
      range: headerRow,
      defval: ''
    });
    
    // Excel file loaded successfully with data rows
    return { success: true, data };
  } catch (error) {
    console.error('Error reading Excel:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('get-excel-sheets', async (event, filePath) => {
  try {
    let fullPath = filePath;
    
    // Handle relative paths for packaged app
    if (!path.isAbsolute(filePath)) {
      const appPath = app.isPackaged ? path.join(process.resourcesPath, 'app') : process.cwd();
      fullPath = path.join(appPath, filePath);
    }
    
    if (!fs.existsSync(fullPath)) {
      throw new Error(`File not found: ${fullPath}`);
    }
    
    const workbook = XLSX.readFile(fullPath);
    return { success: true, sheets: workbook.SheetNames };
  } catch (error) {
    console.error('Error getting Excel sheets:', error);
    return { success: false, error: error.message };
  }
});



ipcMain.handle('save-draft', async (event, data) => {
  try {
    const { filePath } = await dialog.showSaveDialog(mainWindow, {
      defaultPath: 'hazid-draft.json',
      filters: [
        { name: 'JSON Files', extensions: ['json'] }
      ]
    });
    
    if (filePath) {
      fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
      return { success: true, path: filePath };
    }
    return { success: false };
  } catch (error) {
    console.error('Error saving draft:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('load-draft', async () => {
  try {
    const { filePaths } = await dialog.showOpenDialog(mainWindow, {
      filters: [
        { name: 'JSON Files', extensions: ['json'] }
      ],
      properties: ['openFile']
    });
    
    if (filePaths.length > 0) {
      const data = fs.readFileSync(filePaths[0], 'utf8');
      const parsedData = JSON.parse(data);
      // Draft data loaded successfully from file system
      return { success: true, data: parsedData };
    }
    return { success: false };
  } catch (error) {
    console.error('Error loading draft:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('select-file', async (event, options) => {
  try {
    const result = await dialog.showOpenDialog(mainWindow, options);
    return result;
  } catch (error) {
    console.error('Error selecting file:', error);
    throw error;
  }
});

// File storage handlers
ipcMain.handle('save-uploaded-file', async (event, fileData) => {
  try {
    // Create uploads directory next to the app
    let uploadsDir;
    if (app.isPackaged) {
      // If app is packaged (distributed), use the app directory
      uploadsDir = path.join(process.resourcesPath, '..', 'uploads');
    } else {
      // If app is in development, use the project root
      uploadsDir = path.join(process.cwd(), 'uploads');
    }
    
    // Create uploads directory if it doesn't exist
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }
    
    // Generate unique filename
    const timestamp = Date.now();
    const fileName = `${timestamp}_${fileData.name}`;
    const filePath = path.join(uploadsDir, fileName);
    
    // Convert base64 to buffer and save file
    const buffer = Buffer.from(fileData.data, 'base64');
    fs.writeFileSync(filePath, buffer);
    
    return { 
      success: true, 
      savedPath: filePath,
      fileName: fileName
    };
  } catch (error) {
    console.error('Error saving uploaded file:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('get-uploads-directory', async () => {
  try {
    let uploadsDir;
    if (app.isPackaged) {
      // If app is packaged (distributed), use the app directory
      uploadsDir = path.join(process.resourcesPath, '..', 'uploads');
    } else {
      // If app is in development, use the project root
      uploadsDir = path.join(process.cwd(), 'uploads');
    }
    return { success: true, path: uploadsDir };
  } catch (error) {
    console.error('Error getting uploads directory:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('export-document', async (event, data) => {
  try {
    const { filePath } = await dialog.showSaveDialog(mainWindow, {
      defaultPath: `HazID_${data.title ? data.title.replace(/[^a-z0-9]/gi, '_') : 'Document'}.docx`,
      filters: [
        { name: 'Word Documents', extensions: ['docx'] }
      ]
    });
    
    if (filePath) {
      // Use the new hazard document generator
      const hazardDocGenerator = require('../public/hazard-document-generator.cjs');
      
      // Generate final DOCX document
      await hazardDocGenerator.generateHazardDocument(data, filePath);
      
      // Generate loadable draft JSON file (same filename with _DRAFT.json suffix)
      const baseName = path.basename(filePath, '.docx');
      const dirName = path.dirname(filePath);
      const draftPath = path.join(dirName, `${baseName}_DRAFT.json`);
      
      // Create draft JSON with current form data
      const draftData = {
        ...data,
        exportedAt: new Date().toISOString(),
        version: '1.0',
        type: 'hazid-draft'
      };
      
      // Save the draft as JSON file
      fs.writeFileSync(draftPath, JSON.stringify(draftData, null, 2), 'utf-8');
      
      return { 
        success: true, 
        path: filePath,
        draftPath: draftPath,
        message: 'Document has been generated successfully!'
      };
    }
    return { success: false };
  } catch (error) {
    console.error('Error exporting document:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('open-external', async (event, url) => {
  try {
    await shell.openExternal(url);
    return { success: true };
  } catch (error) {
    console.error('Error opening external URL:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('show-message-dialog', async (event, options) => {
  try {
    const result = await dialog.showMessageBox(mainWindow, {
      type: options.type || 'info',
      title: options.title || 'HazID Generator',
      message: options.message,
      detail: options.detail,
      buttons: options.buttons || ['OK']
    });
    return { success: true, response: result.response };
  } catch (error) {
    console.error('Error showing message dialog:', error);
    return { success: false, error: error.message };
  }
});

// Handle app ready
app.on('ready', () => {
  // Electron application initialized and ready
});